#!/usr/local/bin/bash
#
# $Id: mk_flux_menu.sh 18 2011-03-09 21:47:56Z mjeffe $
#
# Another bug-ugly utility from Matt's code archive.
#
# Add an entry for each server found in ~/.wmx/servers/ to the fluxbox menu
#

#set -x

basedir=$HOME/.wmx/servers
out=$basedir/fluxbox_servers.menu
all=$basedir/fluxbox_servers.menu.all
indent="   "
this=`basename $0`

mkmenu()
{
   local d="$1"
   cd $d
   if [ $? -ne 0 ]; then echo "Can't cd to $dir"; exit 1; fi
   for f in *; do
      if [ $f = $this ]; then
         continue
      elif [ -d $f ]; then
         echo "${indent}[submenu] ($f)" >> $out
         indent="$indent   "
         mkmenu $d/$f
         indent=${indent%   }
         echo "${indent}[end]" >> $out
      elif [ -x $f ]; then
         echo "${indent}[exec] (${f#_}) {$d/$f}" >> $out
         echo "   [exec] (${f#_}) {$d/$f}" >> $all
      fi
   done
   cd ..
}


# start the main menu
echo "# generated by `basename $0` on `date`" > $out
echo "[begin] (Servers)" >> $out

# start the all submenu file
echo "# generated by `basename $0` on `date`" > $all
echo "[begin] (All Servers)" >> $all

mkmenu $basedir

# end the all submenu file
echo "[end]" >> $all

# include the all submenu file
echo "${indent}[separator]" >> $out
echo "${indent}[submenu] (all servers)" >> $out
echo "${indent}   [include] ($all)" >> $out
echo "${indent}[end]" >> $out

# add this script as the final entry
echo "   [exec] ($this) {$basedir/$this}" >> $out

# end the main menu
echo "[end]" >> $out


